import * as T from 'three';
// Generated pose atlases are blended in the shader; the physical camera and ball remain 3D.
export function characterSprite(url:string,columns=4,rows=2,size=2.7){
 const texture=new T.TextureLoader().load(url,()=>window.dispatchEvent(new Event('resize')));texture.colorSpace=T.SRGBColorSpace;texture.minFilter=T.LinearFilter;texture.magFilter=T.LinearFilter;texture.generateMipmaps=false;
 const material=new T.ShaderMaterial({transparent:true,depthWrite:true,side:T.DoubleSide,uniforms:{extended:{value:url.includes('batter16')?1:0},atlas:{value:texture},grid:{value:new T.Vector2(columns,rows)},pose:{value:0},alpha:{value:1},trimImpact:{value:url.includes('batter16')?1:0}},vertexShader:`varying vec2 vUv; uniform float extended; void main(){vUv=vec2(uv.x*(1.+extended*.08),uv.y); gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform sampler2D atlas; uniform vec2 grid; uniform float pose; uniform float alpha; uniform float trimImpact; varying vec2 vUv; vec4 frame(float i){if(vUv.x>1. && !(trimImpact>.5 && (i==9.||i==10.) && vUv.x<1.075))return vec4(0.);if(trimImpact>.5 && (i==10.||i==11.) && vUv.x<.10)return vec4(0.);vec2 cell=vec2(mod(i,grid.x),grid.y-1.-floor(i/grid.x));vec2 uv=(cell+vec2(clamp(vUv.x,.002,1.074),clamp(vUv.y,.002,.998)))/grid;return texture2D(atlas,uv);}void main(){float a=floor(pose+.5);float b=min(a+1.,grid.x*grid.y-1.);vec4 x=frame(a);vec4 y=frame(b);float t=0.;vec4 c=mix(vec4(x.rgb*x.a,x.a),vec4(y.rgb*y.a,y.a),t);if(c.a<.015)discard;gl_FragColor=vec4(c.rgb/max(c.a,.001),c.a*alpha);#include <colorspace_fragment>
}`.replace(';#include',';\n#include')});
 const ext=url.includes('batter16')?1.08:1;const geometry=new T.PlaneGeometry(size*ext,size);geometry.translate(size*(ext-1)/2,size*.5,0);const mesh=new T.Mesh(geometry,material);mesh.frustumCulled=false;
 return {mesh,set(frame:number,camera:T.Camera){material.uniforms.pose.value=Math.max(0,Math.min(columns*rows-1,frame));mesh.quaternion.copy(camera.quaternion);},dispose(){texture.dispose();geometry.dispose();material.dispose();}};
}
