name = "enjoy-school-notices"
main = "notion-school-worker.js"
compatibility_date = "2026-06-22"

[vars]
ANDONG_DATABASE_ID = "387e0767-14e4-80b4-b599-daa9d1085480"
# WOOSONG_DATABASE_ID = "YOUR_WOOSONG_NOTION_DATABASE_ID"
# GYEONGSANG_DATABASE_ID = "YOUR_GYEONGSANG_NOTION_DATABASE_ID"
# SILLA_DATABASE_ID = "YOUR_SILLA_NOTION_DATABASE_ID"
# GWANGJU_DATABASE_ID = "YOUR_GWANGJU_NOTION_DATABASE_ID"
# YEUNGNAM_DATABASE_ID = "YOUR_YEUNGNAM_NOTION_DATABASE_ID"
